/**
 * Generates src/generated/webhook-events.ts from spec/webhook-events.json
 * (vendored by fetch-webhook-catalog.ts).
 *
 * Each event's JSON Schema (draft-07, plain constructs only) becomes a payload
 * type. Payloads that carry a `type` property get it narrowed to the event
 * name literal — that property is what SpacebringWebhooks.on() dispatches on.
 * Unknown schema constructs fail the build, same contract as the facade
 * generator.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const CATALOG_PATH = join(ROOT, "spec", "webhook-events.json");
const OUT_PATH = join(ROOT, "src", "generated", "webhook-events.ts");

interface JsonSchema {
  type?: string | string[];
  properties?: Record<string, JsonSchema>;
  required?: string[];
  items?: JsonSchema;
  enum?: unknown[];
  description?: string;
  default?: unknown;
}

interface CatalogEventType {
  name: string;
  description: string;
  deprecated: boolean;
  schemas: Record<string, { properties?: Record<string, JsonSchema>; required?: string[] } & JsonSchema> | null;
}

const catalog: CatalogEventType[] = JSON.parse(readFileSync(CATALOG_PATH, "utf8"));

function fail(message: string): never {
  console.error(message);
  process.exit(1);
}

function typeName(eventName: string): string {
  return (
    eventName
      .split(/[._]/)
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
      .join("") + "Event"
  );
}

function docLine(schema: JsonSchema, indent: string): string {
  const description = schema.description?.trim();
  return description ? `${indent}/** ${description.replace(/\*\//g, "*\\/")} */\n` : "";
}

function tsType(schema: JsonSchema | undefined, path: string, indent: string): string {
  if (!schema || Object.keys(schema).length === 0) return "unknown";
  const { type } = schema;
  if (Array.isArray(type)) {
    return type
      .map((single) => (single === "null" ? "null" : tsType({ ...schema, type: single }, path, indent)))
      .join(" | ");
  }
  if (schema.enum) return schema.enum.map((value) => JSON.stringify(value)).join(" | ");
  switch (type) {
    case "string":
      return "string";
    case "integer":
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "array": {
      const item = tsType(schema.items, `${path}[]`, indent);
      return item.includes("|") || item.includes("{") ? `(${item})[]` : `${item}[]`;
    }
    case "object":
    case undefined: {
      if (!schema.properties) {
        if (type === "object") return "Record<string, unknown>";
        return fail(`Unhandled schema at ${path}: ${JSON.stringify(schema).slice(0, 120)}`);
      }
      const required = new Set(schema.required ?? []);
      const inner = indent + "  ";
      const props = Object.entries(schema.properties)
        .map(([key, propSchema]) => {
          const optional = required.has(key) ? "" : "?";
          return `${docLine(propSchema, inner)}${inner}${JSON.stringify(key)}${optional}: ${tsType(propSchema, `${path}.${key}`, inner)};`;
        })
        .join("\n");
      return `{\n${props}\n${indent}}`;
    }
    default:
      return fail(`Unhandled schema type "${type}" at ${path}`);
  }
}

function latestSchema(event: CatalogEventType): JsonSchema | undefined {
  if (!event.schemas) return undefined;
  const versions = Object.keys(event.schemas).sort((a, b) => Number(a) - Number(b));
  return versions.length > 0 ? event.schemas[versions[versions.length - 1]] : undefined;
}

const HEADER = `// AUTO-GENERATED by codegen/generate-webhooks.ts — DO NOT EDIT.\n// Regenerate with \`npm run generate:webhooks\`.\n\n`;

const declarations: string[] = [];
const mapEntries: string[] = [];
const routable: string[] = [];

for (const event of catalog) {
  const name = typeName(event.name);
  const schema = latestSchema(event);
  const doc =
    `/**\n * Payload of the \`${event.name}\` webhook event.\n` +
    (event.deprecated ? ` *\n * @deprecated Marked as deprecated in the event catalog.\n` : "") +
    ` */\n`;

  if (!schema) {
    declarations.push(`${doc}export type ${name} = Record<string, unknown>;\n`);
  } else {
    if (schema.type !== "object" || !schema.properties) fail(`Event ${event.name}: top-level schema is not an object`);
    // The `type` property carries the event name — narrow it to the literal so
    // the union discriminates and on() dispatch is type-aligned.
    const properties = { ...schema.properties };
    if (properties.type) {
      routable.push(event.name);
      properties.type = { ...properties.type, enum: [event.name] };
    }
    const body = tsType({ ...schema, properties }, event.name, "");
    declarations.push(`${doc}export interface ${name} ${body}\n`);
  }
  mapEntries.push(`  ${JSON.stringify(event.name)}: ${name};`);
}

const source =
  HEADER +
  declarations.join("\n") +
  `\n/** Event name -> payload type for every webhook event in the catalog. */\n` +
  `export interface WebhookEventMap {\n${mapEntries.join("\n")}\n}\n\n` +
  `export type WebhookEventType = keyof WebhookEventMap;\n\n` +
  `/** Events whose payload carries a \`type\` field — the ones on() can dispatch. */\n` +
  `export type RoutableWebhookEventType =\n${routable.map((name) => `  | ${JSON.stringify(name)}`).join("\n")};\n\n` +
  `export type SpacebringWebhookEvent = WebhookEventMap[WebhookEventType];\n`;

writeFileSync(OUT_PATH, source);
console.log(`Generated webhook types for ${catalog.length} events (${routable.length} routable).`);
