/**
 * Generates the nested resource facade (src/generated/resources/) from spec/openapi.json.
 *
 * Naming is fully deterministic:
 * - Namespaces come from path segments before "/v1" (plus literal sub-collections
 *   such as "items" that have their own "/{id}" paths).
 * - Collection GET -> list (+ iterate when the response is paginated), POST -> create.
 * - Item GET/PUT/PATCH/DELETE -> get/update/update/delete.
 * - Action segments (e.g. "/pay", "/cancel_payment") -> camelCase verb, validated
 *   against the operationId's leading verb.
 * - Anything that matches no rule is emitted under its full operationId and reported,
 *   so no operation is ever dropped silently.
 *
 * This file is the orchestrator; the moving parts live next to it:
 * - spec.ts     — spec loading, $ref resolution, shared types, warnings
 * - analyze.ts  — operation analysis (namespaces, envelopes) + method naming
 * - entities.ts — entity aliases + named query interfaces
 * - emit.ts     — per-operation method code emission
 * - tree.ts     — namespace tree + rendering
 */
import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { type AnalyzedOp, analyze, methodName } from "./facade/analyze.js";
import { emitMethod, successJsonType } from "./facade/emit.js";
import {
  buildQueryTypes,
  type Entity,
  type EntityCandidate,
  entityBase,
  methodPriority,
  resolveEntities,
} from "./facade/entities.js";
import { pascalCase } from "./facade/naming.js";
import { HTTP_METHODS, ROOT, spec, specPaths, warnings } from "./facade/spec.js";
import { nodeFor, nodeUses, renderNode, roots, type TreeNode } from "./facade/tree.js";

const OUT_DIR = join(ROOT, "src", "generated", "resources");

// Pass 1: analyze every operation and collect entity candidates.
interface OpRecord {
  analyzed: AnalyzedOp;
  name: string;
  node: TreeNode;
}

let operationCount = 0;
const records: OpRecord[] = [];
const entityCandidates: EntityCandidate[] = [];

for (const path of specPaths) {
  for (const method of HTTP_METHODS) {
    const op = spec.paths[path][method];
    if (!op) continue;
    operationCount += 1;
    const analyzed = analyze(path, method, op);
    const node = nodeFor(analyzed.namespace);
    const name = methodName(analyzed);
    records.push({ analyzed, name, node });

    const responseType = successJsonType(op);
    const root = analyzed.namespace[0];
    // Prefer the canonical component schema (stable, matches the API's own type
    // names) over reaching through this operation's response envelope, which is
    // fragile if the endpoint is renamed/removed. Falls back to the envelope
    // form when the response property is inline rather than a $ref.
    const componentExpr = (ref: string) => `NonNullable<components["schemas"]["${ref}"]>`;
    if (analyzed.unwrapKey) {
      entityCandidates.push({
        node,
        root,
        namespace: analyzed.namespace,
        base: entityBase(analyzed.unwrapKey),
        expr: analyzed.unwrapSchemaRef
          ? componentExpr(analyzed.unwrapSchemaRef)
          : `NonNullable<${responseType}["${analyzed.unwrapKey}"]>${analyzed.unwrapIsArray ? "[number]" : ""}`,
        priority: methodPriority(name),
        opId: op.operationId,
      });
    }
    if (analyzed.pagination) {
      entityCandidates.push({
        node,
        root,
        namespace: analyzed.namespace,
        base: entityBase(analyzed.pagination.itemsKey),
        expr: analyzed.pagination.itemsSchemaRef
          ? componentExpr(analyzed.pagination.itemsSchemaRef)
          : `NonNullable<${responseType}["${analyzed.pagination.itemsKey}"]>[number]`,
        priority: methodPriority(name),
        opId: op.operationId,
      });
    }
  }
}

const entitiesByNode = resolveEntities(entityCandidates);

const allEntityNames = new Set(
  [...entitiesByNode.values()].flatMap((entities) => [...entities.values()].map((entity) => entity.name)),
);
const { queryTypesByOp, queryTypesByRoot } = buildQueryTypes(records, allEntityNames);

// Pass 2: emit methods with entity aliases resolved.
for (const { analyzed, name, node } of records) {
  for (const emitted of emitMethod(analyzed, name, entitiesByNode.get(node), queryTypesByOp.get(analyzed.op.operationId)?.name)) {
    const clash = node.methods.find((m) => m.name === emitted.name);
    if (clash) {
      console.error(`Name clash in ${analyzed.namespace.join(".")}: ${emitted.name} (${analyzed.op.operationId})`);
      process.exit(1);
    }
    node.methods.push(emitted);
  }
}

rmSync(OUT_DIR, { recursive: true, force: true });
mkdirSync(OUT_DIR, { recursive: true });

const HEADER = `// AUTO-GENERATED by codegen/generate-facade.ts — DO NOT EDIT.\n// Regenerate with \`npm run generate:facade\`.\n`;

const allEntities = [...entitiesByNode.values()].flatMap((entities) => [...entities.values()]);
const entitiesByRoot = new Map<string, Entity[]>();
for (const entity of allEntities) {
  const group = entitiesByRoot.get(entity.root) ?? [];
  group.push(entity);
  entitiesByRoot.set(entity.root, group);
}

const rootNames = [...roots.keys()].sort();
for (const rootName of rootNames) {
  const node = roots.get(rootName)!;
  const factory = `create${pascalCase(rootName)}`;
  const entityDefs = (entitiesByRoot.get(rootName) ?? [])
    .sort((a, b) => a.name.localeCompare(b.name))
    .map(
      (entity) =>
        `/** A ${entity.name} entity as returned by the Spacebring API. */\n` + `export type ${entity.name} = ${entity.expr};\n`,
    )
    .join("\n");
  const coreImports = [
    ...(nodeUses(node, "usesPaginate") ? ["paginate"] : []),
    "unwrap",
    ...(nodeUses(node, "usesUnwrapProp") ? ["unwrapProp"] : []),
    "type SpacebringDefaults",
    "type SpacebringRequestOptions",
  ].join(", ");
  const queryDefs = (queryTypesByRoot.get(rootName) ?? [])
    .sort((a, b) => a.name.localeCompare(b.name))
    .map((query) => query.decl)
    .join("\n");
  const body =
    (entityDefs ? entityDefs + "\n" : "") +
    (queryDefs ? queryDefs + "\n" : "") +
    `export function ${factory}(client: Client<paths>, defaults: SpacebringDefaults) {\n` +
    `  return {\n` +
    renderNode(node, "    ") +
    `\n  };\n}\n`;
  // With named query types some files no longer reference operations[...] at all;
  // entities that resolve to a component schema reference components[...] instead.
  const schemaImports = [
    ...(body.includes("components[") ? ["components"] : []),
    ...(body.includes("operations[") ? ["operations"] : []),
    "paths",
  ].join(", ");
  const source =
    HEADER +
    `import type { Client } from "openapi-fetch";\n` +
    `import { ${coreImports} } from "../../core.js";\n` +
    `import type { ${schemaImports} } from "../schema.js";\n\n` +
    body;
  writeFileSync(join(OUT_DIR, `${rootName}.ts`), source);
}

const indexSource =
  HEADER +
  `import type { Client } from "openapi-fetch";\n` +
  `import type { SpacebringDefaults } from "../../core.js";\n` +
  `import type { paths } from "../schema.js";\n` +
  rootNames.map((name) => `import { create${pascalCase(name)} as ${name}Group } from "./${name}.js";\n`).join("") +
  `\nexport function createResources(client: Client<paths>, defaults: SpacebringDefaults) {\n` +
  `  return {\n` +
  rootNames.map((name) => `    ${name}: ${name}Group(client, defaults),\n`).join("") +
  `  };\n}\n\n` +
  `export type SpacebringResources = ReturnType<typeof createResources>;\n`;
writeFileSync(join(OUT_DIR, "index.ts"), indexSource);

// Named entity aliases and query interfaces re-exported for consumers
// (import type { Booking, GetBookingsQuery } ...).
const entitiesSource =
  HEADER +
  rootNames
    .map((name) => {
      const names = [
        ...(entitiesByRoot.get(name) ?? []).map((entity) => entity.name),
        ...(queryTypesByRoot.get(name) ?? []).map((query) => query.name),
      ]
        .sort()
        .join(", ");
      return names ? `export type { ${names} } from "./resources/${name}.js";\n` : "";
    })
    .join("");
writeFileSync(join(ROOT, "src", "generated", "entities.ts"), entitiesSource);

// Keep the coverage numbers in the README in sync with the spec.
const README_PATH = join(ROOT, "README.md");
const readme = readFileSync(README_PATH, "utf8");
const coverage = `<!-- coverage -->${operationCount} operations across ${rootNames.length} resource groups<!-- /coverage -->`;
const updatedReadme = readme.replace(/<!-- coverage -->.*?<!-- \/coverage -->/s, coverage);
if (!updatedReadme.includes(coverage)) {
  console.error("README.md is missing the <!-- coverage --> markers; coverage numbers not updated.");
  process.exit(1);
}
if (updatedReadme !== readme) writeFileSync(README_PATH, updatedReadme);

console.log(`Generated ${rootNames.length} resource files covering ${operationCount} operations.`);
if (warnings.length > 0) {
  console.warn(`\n${warnings.length} warning(s):`);
  for (const warning of warnings) console.warn(`  - ${warning}`);
}
